# Generated by Django 5.1.4 on 2025-01-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_top_product_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_colors',
            field=models.ManyToManyField(blank=True, related_name='product_color', to='store.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_size',
            field=models.ManyToManyField(blank=True, related_name='product_size', to='store.size'),
        ),
    ]
