version: '26.0'

services:
  web:
    image: your-django-image
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    # depends_on:
    #   - db
    environment:
      - PROTOCOL=http
      - DOMAIN=localhost:8000
      - "DJANGO_SECRET_KEY=${DOCKER_COMPOSE_DJANGO_SECRET_KEY}"
      - "DJANGO_DEBUG=${DOCKER_COMPOSE_DJANGO_DEBUG}"
      # - "DB_NAME=${DB_NAME}"
      # - "DB_USER=${DB_USER}"
      # - "DB_PASSWORD=${DB_PASSWORD}"
      # - "DB_HOST=${DB_HOST}"
      # - "DB_PORT=${DB_PORT}"
  # db:
  #   image: postgres:14
  #   environment:
  #     - "POSTGRES_HOST_AUTH_METHOD=trust"